export {Listar} from './Listar'
export {Ficha} from './Ficha'
export {Delete} from './Deletar'
export {Filtro} from './Filtro'
export {Criar} from './Criar'
export {Editar} from './Editar'
export {Dashboard} from './dashBoard'